### ISSUE TITLE
2022.8 deletes the tag properties if it's empty, Dynamo should check for the missing property.

### ISSUE THREAD

**Issue by patchuby** [JujuAdams/Dynamo#11]
The specific crash occured on line 23 of the DynamoFindNotes function.
![image](https://user-images.githubusercontent.com/9586594/194699496-4afb8044-2c24-4363-babb-83ef56fd40e6.png)

Proposed fix for the line 23: 

`var _tags = _json[$ "tags"] ?? [];`

**Comment by patchuby** [comment]
Proof for the assertion in the title, this happened to every asset in GM : 
<img width="1768" alt="image" src="https://user-images.githubusercontent.com/9586594/194699756-67790820-a473-4da3-a57c-5662c1ebeec5.png">
Happened to @Damon too on the discord.

**Comment by JujuAdams** [comment]
Fixed in 2.2.0
