### ISSUE TITLE
Features: Constant and Basic operator 

### ISSUE THREAD

**Issue by MichelVGameMaker** [JujuAdams/Dynamo#16]
Hi Juju,

Just an idea.

Actually two fetaures for the parser:
1-ability to parse the following operators + - * /
2-ability to add constant to DYNAMO knowledge, and then the parser can decode the constant to the associated value 

Why I encountered this ?
In my game I state all range / distance values in number of tiles. So everywhere it's instructions like detect_range = 8 * TILE_SIZE etc... TILE_SIZE being a macro. I am more confortable with understanding the value logicv by expressing it that way.
I cannot use this syntax in my 'dynamo-watched' database.gml

DYNAMO is alreaddy great like it is ! 

M.

**Comment by JujuAdams** [comment]
Dynamo relies on SNAP's GML parser so this is really a [feature request for SNAP](https://github.com/JujuAdams/SNAP/issues/43).

**Comment by JujuAdams** [comment]
Made a lot of progress! Gonna wind the latest beta of SNAP into Dynamo and see where we get.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Dynamo/releases/tag/4.0.0

Call `DynamoScriptEnvSetVariable("TILE_SIZE", TILE_SIZE)` to set up a value for a variable whent Dynamo parses.

This is an alpha as I've not done a whole load of testing. Please file new tickets if you run into any bugs.
