### ISSUE TITLE
4.0.0 script parsing '_' underscore

### ISSUE THREAD

**Issue by MichelVGameMaker** [JujuAdams/Dynamo#17]
Hello Juju

So I tested the 4.0.0 from here https://github.com/JujuAdams/Dynamo/releases/tag/4.0.0.

- Tested basic operations, also in a struct or in an array and everything worked.
- The issue I found is with underscore.
  I got it to work by removing `|| (_byte == ord("_")) ` line 174 in **__DynamoParseGML.gml**
  But I am not sure if it's ok.

I created the issue in the 4.0.0:
In TestScript.gml
if I changeg the first variable from global.testData to `global.test_Data`, it gives the message: `Variable "global.test" has no alias`

It will do the same if inside I use _ inside a struct.
```
global.structArrayThing = {
    my_underscore: 1,
    variable: 1
};
```

Also in the demo, as GM does not string(struct) anymore, in **oTest draw event**
you could replace:
`_string += "global.structArrayThing = " + string(global.structArrayThing) + "\n";`
by
`_string += "global.structArrayThing = " + json_stringify(global.structArrayThing) + "\n";`
(Big added value :P)

**Comment by JujuAdams** [comment]
Are you using LTS?

**Comment by MichelVGameMaker** [comment]
Yes I am

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Dynamo/releases/tag/4.0.1
