### ISSUE TITLE
4.0.0 script parsing - object index, GM constants

### ISSUE THREAD

**Issue by MichelVGameMaker** [JujuAdams/Dynamo#18]
Me again,

I found another thing, in the 4.0.0 from here https://github.com/JujuAdams/Dynamo/releases/tag/4.0.0.

Previously (and I was not adding infinity to __DynamoGMLConstants), the script parser would interpret the constant **_infinity_**. Now it gives the error:
`Variable "infinity" has no alias.`

Also;

Previously the script parser would interpret an object index (oLVL_Solid_All in my case). Now it gives the error:
`Variable "oLVL_Solid_All" has no alias`

Of course both can be fixed by the user by adding all required constants manually in __DynamoGMLConstants. Just reporting

**Comment by MichelVGameMaker** [comment]
oh and for the object_index **seems** to be fixed by re-using the try_to_find_asset intructions from  the previous version ... But I am sure there is a reson for it not being in 4.0.0.
Line 897 in __DynamoParseGML.gml.


```
               // first pass using the code from the try_to_find_asset  
                var _index = asset_get_index(_tokenValue); 
		if (_index >= 0) 
		{
			_value = _index;	
		}


		else if (variable_struct_exists(_globalVariableStruct, _tokenValue))
                {
                    _value = _globalVariableStruct[$ _tokenValue]();
                }
                else if (not variable_struct_exists(_aliasStruct, _tokenValue))
                {
                    __DynamoError("Variable \"", _tokenValue, "\" has no alias");
                }
```

**Comment by JujuAdams** [comment]
`infinity` is a missing keyword, not intentional.

Not being able to reference assets was a deliberate choice for SNAP (security) but not a helpful choice for Dynamo.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Dynamo/releases/tag/4.0.1

**Comment by MichelVGameMaker** [comment]
Thank you Juju.
I knew there would be a reason for the asset.
Thanks for upgrading Dynamo so fast.
