### ISSUE TITLE
sprite_add using json files doesn't work

### ISSUE THREAD

**Issue by zackbertok** [JujuAdams/Dynamo#9]
Importing a spine (json) animation using sprite_add doesn't work using Dynamo.

1) Place any .atlas, .json, and .png file in the datafilesDynamo folder.
2) Attempt to import using sprite_add("skeleton.json", 0, false, true, 0, 0)	

The resulting sprite always has dimensions of 1x1 and isn't visible despite being correctly assigned a sprite index.

**Comment by JujuAdams** [comment]
Rewrote Dynamo ahead of my talk on Friday so I suspect this bug is no longer relevant in v2
